app/blueprints/race_times.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from app.db_connect import get_db
from itertools import groupby
from flask import jsonify

race_times = Blueprint('race_times', __name__)

@race_times.route('/race_time/<race_id>', methods=['GET', 'POST'])
def race_time(race_id):
    rosters = fetch_rosters_from_db()
    race_types = fetch_race_types_from_db()
    if request.method == 'POST':
        # Retrieve form data
        race_type_id = request.form['race_type_id']

        # Map race_type_id to the corresponding field in the runners table
        race_type_field_mapping = {
            '1': 'time_800_pr',
            '2': 'time_1600_pr',
            '4': 'time_3200_pr',
            '3': 'time_5k_pr'
        }

        # Iterate over the form data
        for key, value in request.form.items():
            if key.startswith('time_') and value:  # Check if value is not empty
                runner_id = key.split('_')[1]
                duration_time = value

                # Insert new race time into the database
                conn = get_db()
                with conn.cursor() as cur:
                    cur.execute("""
                        INSERT INTO race_detail (runner_id, race_id, race_type_id, duration_time)
                        VALUES (%s, %s, %s, %s)
                    """, (runner_id, race_id, race_type_id, duration_time))

                    # Fetch the runner's profile
                    cur.execute("SELECT * FROM runners WHERE runner_id=%s", (runner_id,))
                    runner = cur.fetchone()

                    # Get the field to update based on the race_type_id
                    field_to_update = race_type_field_mapping[race_type_id]

                    # Check if the field is None or empty or if the new time is lower
                    if runner[field_to_update] in [None, ''] or runner[field_to_update] > duration_time:
                        # If either condition is true, update the runner's profile
                        cur.execute(f"UPDATE runners SET {field_to_update}=%s WHERE runner_id=%s",
                                    (duration_time, runner_id))
                    conn.commit()

        # Redirect to the same page to see the updated race times
        return redirect(url_for('race_times.race_time', race_id=race_id))


    else:  # GET method
        race_info = fetch_race_info_from_db(race_id)
        conn = get_db()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT
                    runners.runner_id,
                    runners.first_name,
                    runners.last_name,
                    runners.gender,
                    race_detail.race_detail_id,
                    race_detail.race_id,
                    race_detail.race_type_id,
                    race_detail.duration_time,
                    race.race_name,
                    race_type.race_type_name,
                    race_type.rank_order
                FROM
                    runners
                JOIN
                    race_detail ON runners.runner_id = race_detail.runner_id
                JOIN
                    race ON race_detail.race_id = race.race_id
                JOIN
                    race_type ON race_detail.race_type_id = race_type.race_type_id
                WHERE
                    race.race_id = %s
                ORDER BY
                    race_type.rank_order,
                    runners.gender,
                    race_detail.duration_time;
            """, (race_id,))
            results = [dict(row) for row in cur.fetchall()]
        # Group the results by race_type_name and then by gender
        grouped_results = {}
        for result in results:
            race_type_name = result['race_type_name']
            if race_type_name not in grouped_results:
                grouped_results[race_type_name] = {}
            gender = result['gender']
            if gender not in grouped_results[race_type_name]:
                grouped_results[race_type_name][gender] = []
            grouped_results[race_type_name][gender].append(result)

        # Sort the groups by gender and then by duration_time
        for race_type, gender_groups in grouped_results.items():
            for gender, runners in gender_groups.items():
                runners.sort(key=lambda x: x['duration_time'])

        return render_template('race_times.html', results=grouped_results, race_info=race_info, rosters=rosters,
                               race_types=race_types)

@race_times.route('/add_race_time/<race_id>', methods=['GET'])
def add_race_time(race_id):
    # Fetch the runners based on the roster_id from the GET parameters
    roster_id = request.args.get('roster_id')
    runners = []
    if roster_id is not None:
        conn = get_db()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT runners.*
                FROM runners
                JOIN roster_detail ON runners.runner_id = roster_detail.runner_id
                WHERE roster_detail.roster_id = %s
            """, (roster_id,))
            runners = [dict(row) for row in cur.fetchall()]

    # Return the runners as a JSON response
    return jsonify(runners)

@race_times.route('/delete_race_time/<race_detail_id>/<race_id>', methods=['POST'])
def delete_race_time(race_detail_id, race_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("DELETE FROM race_detail WHERE race_detail_id = %s", (race_detail_id,))
        conn.commit()

    return redirect(url_for('race_times.race_time', race_id=race_id))

@race_times.route('/update_race_time/<race_detail_id>/<race_id>', methods=['POST'])
def update_race_time(race_detail_id, race_id):
    runner_id, race_type_id = fetch_runner_id_from_db(race_detail_id)

    duration_time = request.form['duration_time']
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("UPDATE race_detail SET duration_time = %s WHERE race_detail_id = %s", (duration_time, race_detail_id))
        conn.commit()

        # Map race_type_id to the corresponding field in the runners table
        race_type_field_mapping = {
            1: 'time_800_pr',
            2: 'time_1600_pr',
            4: 'time_3200_pr',
            3: 'time_5k_pr'
        }

        # Fetch the runner's profile
        cur.execute("SELECT * FROM runners WHERE runner_id=%s", (runner_id,))
        runner = cur.fetchone()

        # Get the field to update based on the race_type_id
        field_to_update = race_type_field_mapping[race_type_id]

        # Check if the field is None or empty or if the new time is lower
        if runner[field_to_update] in [None, ''] or runner[field_to_update] > duration_time:
            # If either condition is true, update the runner's profile
            cur.execute(f"UPDATE runners SET {field_to_update}=%s WHERE runner_id=%s",
                        (duration_time, runner_id))
        conn.commit()

    return redirect(url_for('race_times.race_time', race_id=race_id))


#### FUNCTIONS ########################################################################################################
#######################################################################################################################

def fetch_rosters_from_db():
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM rosters ORDER BY roster_year DESC")
        return cur.fetchall()

def fetch_race_types_from_db():
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM race_type")
        return cur.fetchall()

def fetch_race_info_from_db(race_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT race_id, race_name, EXTRACT(YEAR FROM race_date) as race_year FROM race WHERE race_id = %s", (race_id,))
        return cur.fetchone()

def fetch_runner_id_from_db(race_detail_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT runner_id, race_type_id FROM race_detail WHERE race_detail_id = %s", (race_detail_id,))
        result = cur.fetchone()
        print(result)
        return result['runner_id'],result['race_type_id']

app/blueprints/races.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.db_connect import get_db

races = Blueprint('races', __name__)

@races.route('/race', methods=['GET', 'POST'])
def race():
    if request.method == 'POST':
        race_location = request.form['race_location']
        race_mile_split_url = request.form['race_mile_split_url']
        race_name = request.form['race_name']
        race_date = request.form['race_date']
        conn = get_db()
        with conn.cursor() as cur:
            cur.execute("INSERT INTO race (race_name, race_date, race_location, race_mile_split_url) VALUES (%s, %s, %s, %s)",
                        (
                            race_name,
                            race_date,
                            race_location,
                            race_mile_split_url
                        ))
            conn.commit()
        flash('Race added successfully')
        return redirect(url_for('races.race'))

    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT EXTRACT(YEAR FROM race_date) as year, race_id, race_name, race_date, race_location, race_mile_split_url FROM race ORDER BY race_date")
        races_by_year = {}
        for row in cur.fetchall():
            year = row['year']
            if year not in races_by_year:
                races_by_year[year] = []
            races_by_year[year].append(row)
    return render_template('races.html', races_by_year=races_by_year)


@races.route('/update_race/<race_id>/', methods=['POST'])
def update_race(race_id):
    race_name = request.form['race_name']
    race_date = request.form['race_date']
    race_location = request.form['race_location']
    race_mile_split_url = request.form['race_mile_split_url']
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("UPDATE race SET race_name=%s, race_date=%s, race_location=%s, race_mile_split_url=%s WHERE race_id=%s",
                    (
                        race_name,
                        race_date,
                        race_location,
                        race_mile_split_url,
                        race_id
                    ))
        conn.commit()
    flash('Race updated successfully')
    return redirect(url_for('races.race'))

@races.route('/delete_race/<race_id>/', methods=['POST'])
def delete_race(race_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("DELETE FROM race WHERE race_id=%s", (race_id,))
        conn.commit()
    flash('Race deleted successfully')
    return redirect(url_for('races.race'))

@races.route('/add_race_times/<race_id>/', methods=['GET', 'POST'])
def add_race_times(race_id):
    pass

app/blueprints/rosters.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.db_connect import get_db
from datetime import datetime

rosters = Blueprint('rosters', __name__)

@rosters.route('/roster', methods=['GET', 'POST'])
def roster():
    if request.method == 'POST':
        conn = get_db()
        with conn.cursor() as cur:
            cur.execute("INSERT INTO rosters (roster_year, roster_season, gender) "
                        "VALUES (%s, %s, %s)",
                        (
                            request.form['roster_year'],
                            request.form['roster_season'],
                            request.form['gender'],
                        ))
            conn.commit()
        flash('Roster added successfully')
        return redirect(url_for('rosters.roster'))
    rosters = get_rosters()
    return render_template('rosters.html', rosters=rosters)

@rosters.route('/update_roster/<roster_id>/', methods=['POST'])
def update_roster(roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("UPDATE rosters SET roster_year=%s, roster_season=%s, gender=%s WHERE roster_id=%s",
                    (
                        request.form['roster_year'],
                        request.form['roster_season'],
                        request.form['gender'],
                        roster_id)
                    )
        conn.commit()
    flash('Roster updated successfully')
    return redirect(url_for('rosters.roster'))

@rosters.route('/delete_roster/<roster_id>/', methods=['POST'])
def delete_roster(roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("DELETE FROM rosters WHERE roster_id=%s", (roster_id,))
        conn.commit()
    flash('Roster deleted successfully')
    return redirect(url_for('rosters.roster'))

@rosters.route('/roster_details/<roster_id>/', methods=['GET', 'POST'])
def roster_details(roster_id):
    if request.method == 'POST':
        conn = get_db()
        with conn.cursor() as cur:
            cur.execute("INSERT INTO roster_detail (roster_id, runner_id) "
                        "VALUES (%s, %s)",
                        (
                            roster_id,
                            request.form['runner_id'],
                        ))
            conn.commit()
        flash('Runner added to roster successfully')
        return redirect(url_for('rosters.roster_details'))
    roster = get_roster_info(roster_id)
    runner_drop = runner_dropdown(roster_id)
    current_roster = get_roster_by_details(roster_id)
    print(current_roster)
    return render_template('roster_details.html', current_roster=current_roster, roster=roster, runner_drop=runner_drop)

@rosters.route('/delete_runner_from_roster/<roster_detail_id>/<roster_id>/', methods=['POST'])
def delete_runner_from_roster(roster_detail_id, roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("DELETE FROM roster_detail WHERE roster_detail_id=%s", (roster_detail_id))
        conn.commit()
    flash('Runner removed from roster successfully')
    return redirect(url_for('rosters.roster_details', roster_id=roster_id))

@rosters.route('/add_runner_to_roster/<roster_id>/', methods=['POST'])
def add_runner_to_roster(roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("INSERT INTO roster_detail (roster_id, runner_id) "
                    "VALUES (%s, %s)",
                    (
                        roster_id,
                        request.form['runner_id'],
                    ))
        conn.commit()
    flash('Runner added to roster successfully')
    return redirect(url_for('rosters.roster_details', roster_id=roster_id))

#### FUNCTIONS ########################################################################################################
#######################################################################################################################
# loads the current rosters
def get_rosters():
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM rosters ORDER BY roster_year DESC, roster_season ASC")
        rosters = cur.fetchall()
    return rosters

# gets the current roster details
def get_roster_info(roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM rosters WHERE roster_id=%s", (roster_id,))
        roster = cur.fetchone()
    return roster

# gets all the runners in a specific roster
def get_roster_by_details(roster_id):
    conn = get_db()
    with conn.cursor() as cur:
        cur.execute("SELECT RD.roster_detail_id, R.first_name, R.last_name, R.grad_year, RD.roster_id "
                    "FROM runners R "
                    "JOIN roster_detail RD ON R.runner_id = RD.runner_id "
                    "WHERE RD.roster_id = %s", (roster_id,))
        roster_details = cur.fetchall()
    return roster_details

# function to select runners for the dropdown in the add modal
def runner_dropdown(roster_id):
    current_year = datetime.now().year
    future_year = current_year + 7
    conn = get_db()
    with conn.cursor() as cur:
        # Fetch the gender of the roster
        cur.execute("SELECT gender FROM rosters WHERE roster_id = %s", (roster_id,))
        roster_gender_result = cur.fetchone()
        print(roster_gender_result)
        if roster_gender_result is None or not isinstance(roster_gender_result, dict):
            return []
        roster_gender = roster_gender_result['gender']
        print(roster_gender)



        # Fetch all runners that match the gender of the roster
        cur.execute("""
            SELECT R.runner_id, R.first_name, R.last_name 
            FROM runners R 
            WHERE R.grad_year BETWEEN %s AND %s 
            AND R.gender = %s 
            AND R.runner_id NOT IN ( 
                SELECT RD.runner_id 
                FROM roster_detail RD 
                WHERE RD.roster_id = %s 
            )
        """, (current_year, future_year, roster_gender, roster_id))
        runner_drop = cur.fetchall()
    return runner_drop

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JC Runners App - {% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Your styles.css -->
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-lg-5">
        <a class="navbar-brand" href="{{ url_for('index') }}">JC Runner</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% block nav_dash1 %}{% endblock %}" href="{{ url_for('runners.runner') }}">Runners</a></li>
                <li class="nav-item"><a class="nav-link {% block nav_yearly1 %}{% endblock %}" href="{{ url_for('rosters.roster') }}">Roster</a></li>
                <li class="nav-item"><a class="nav-link {% block nav_portfolio1 %}{% endblock %}" href="{{ url_for('races.race') }}">Race</a></li>
                <li class="nav-item"><a class="nav-link {% block nav_networth1 %}{% endblock %}" href="{{ url_for('results.result') }}">Results</a></li>
            </ul>
            <hr>

        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; JC Runner 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <!-- Core theme JS-->
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %} Runners {% endblock %}


{% block content %}

<!-- About section-->
<section id="about">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-10">



               <h1>Welcome to PaceSetters!</h1>
  <p><strong>Catchphrase: "Run Your Race, Set Your Pace!"</strong></p>

  <p>Welcome to PaceSetters, where every step forward is a step towards achieving your personal best. Whether you're gearing up for your first 5k or you're an experienced marathoner looking to shatter personal records, PaceSetters is here to guide you on your journey. With state-of-the-art tracking, personalized training plans, and a supportive community at your fingertips, we're more than just an app; we're your newest running partner.</p>

  <p>At PaceSetters, we understand that every runner's journey is unique. That's why our application offers customizable features that cater to your individual goals, fitness level, and schedule. From interactive routes that challenge and inspire, to detailed progress tracking that celebrates every milestone, we're with you every step of the way. Plus, with access to our global community of fellow runners, you'll find motivation, advice, and perhaps even some friendly competition to keep you moving forward.</p>

  <p>Join us at PaceSetters and embrace the journey ahead. Because here, it's not just about the distance you cover; it's about the experiences you gain, the limits you push, and the community you build. <strong>Run Your Race, Set Your Pace!</strong> Let's lace up and explore what's possible together.</p>





            </div>
        </div>
    </div>
</section>





{% endblock %}

app/templates/race_times.html
{% extends "base.html" %}

{% block title %} Race Times {% endblock %}

{% block content %}

<!-- Header-->

        <!-- About section-->
        <section id="about">
            <div class="container px-4">
                <div class="row gx-4 justify-content-center">
                    <div class="col-lg-10">
                    <h1>{{ race_info.race_year }} {{ race_info.race_name }} Race Times</h1>

                        <button type="button" class="btn btn-success btn-lg btn-block" data-bs-toggle="modal" data-bs-target="#add_race_times">Add Race Times</button>
                        </h1>
                        <br>
                        <div class="modal fade" id="add_race_times" aria-labelledby="add_account_typeLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="add_modalLabel">Add Race Times</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="{{ url_for('race_times.race_time', race_id=race_info.race_id) }}" method="POST">
                                    <input type="hidden" id="race_id" name="race_id" value="{{ race_info.race_id }}">
                                    <input type="hidden" id="race_type_id" name="race_type_id">
                                    <div class="modal-body">
                                        <p>
                                            <label for="roster">Choose a roster:</label>
                                            <select name="roster_id" id="roster">
                                                    <option value="" disabled selected>Select a Roster</option>
                                                {% for roster in rosters %}
                                                    <option value="{{ roster.roster_id }}" {% if roster.roster_id|string == request.args.get('roster_id') %}selected{% endif %}>{{ roster.roster_year }} {{ roster.roster_season }} {{ roster.gender }}</option>
                                                {% endfor %}
                                            </select>
                                        </p>
                                        <p>
                                            <label for="race_type">Choose a race type:</label>
                                            <select name="race_type_id" id="race_type">
                                                {% for race_type in race_types %}
                                                    <option value="{{ race_type.race_type_id }}">{{ race_type.race_type_name }}</option>
                                                {% endfor %}
                                            </select>
                                        </p>
                                        <table id="runners_table" class="table">
                                            <!-- This table will be populated with JavaScript -->
                                        </table>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        <button type="submit" class="btn btn-primary">Add Race Times</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                        {% for race_type_name, race_results in results.items() %}
                        <h2>{{ race_type_name }}</h2>
                        {% for gender, gender_results in race_results.items() %}
                            <h4>{{ gender }}</h4>
                            <table class="table">
                                <thead>
                                    <th scope="col">Name</th>
                                    <th scope="col">Time</th>
                                    <th scope="col">Actions</th>
                                </thead>
                                {% for result in gender_results %}
                                    <tr>
                                        <td align="left">{{ result.first_name }} {{ result.last_name }}</td>
                                        <td align="left">{{ result.duration_time }}</td>
                                        <td>
                                            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#update_modal{{result.race_detail_id}}">Update Race</button>
                                            <div class="modal fade" id="update_modal{{result.race_detail_id}}" aria-labelledby="update_modalLabel" aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="update_modalLabel">Update Time</h5>
                                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                            </div>
                                                            <form action="{{ url_for('race_times.update_race_time', race_detail_id=result.race_detail_id, race_id=race_info.race_id) }}" method="POST">
                                                                <div class="modal-body">
                                                                    <p>
                                                                        <label for="duration_time_update">Time:</label><br>
                                                                        <input id="duration_time_update" name="duration_time" value="{{ result.duration_time }}">
                                                                    </p>
                                                                    <p>
                                                                        <input type="submit" class="btn btn-success" value="Update Race">
                                                                    </p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                                </div>
                                                            </form>

                                                        </div>
                                                    </div>
                                            </div>
                                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete_modal{{result.race_detail_id}}">Delete</button>

                            <!-- DELETE MODAL -->
                                    <div class="modal fade" id="delete_modal{{result.race_detail_id}}" aria-labelledby="delete_modalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="delete_modalLabel">Delete Time</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to delete <strong>{{ result.first_name }}'s </strong> time?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                    <form action="{{url_for('race_times.delete_race_time', race_detail_id=result.race_detail_id, race_id=race_info.race_id)}}" method="POST">
                                                        <input type="submit" class="btn btn-primary" value="Delete">
                                                    </form>
                                              </div>
                                            </div>
                                        </div>
                                    </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% endfor %}
                        {% endfor %}



                        <br>
                       <br>
                    </div>
                </div>
            </div>
        </section>


<script src="{{ url_for('static', filename='js/add_time.js') }}"></script>


{% endblock %}